import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
        <Script src="/ace-builds/src-noconflict/ace.js" type="text/javascript" charSet="utf-8"></Script>
        </head>
      <body className={`${inter.className} bg-black`}>{children}</body>
    </html>
  );
}
